# Generated by Django 4.0.3 on 2022-04-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('mts_id', models.CharField(max_length=191, primary_key=True, serialize=False, unique=True, verbose_name='MTS ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'db_table': 'buttons',
            },
        ),
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('click', 'click'), ('double_click', 'double_click'), ('long_press', 'long_press')], default='click', max_length=12, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('button', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guard.button')),
            ],
            options={
                'verbose_name': 'Button click',
                'verbose_name_plural': 'Button clicks',
                'db_table': 'button_clicks',
            },
        ),
    ]
