# Generated by Django 4.0.3 on 2022-04-10 07:23

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326, verbose_name='Geolocation'),
        ),
    ]
